// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ImageService.proto

package com_skynet_dipper_commons_grpc_image

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

import (
	"github.com/apache/dubbo-go/protocol"
	dgrpc "github.com/apache/dubbo-go/protocol/grpc"
	"github.com/apache/dubbo-go/protocol/invocation"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImageData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Photo                []byte   `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageData) Reset()         { *m = ImageData{} }
func (m *ImageData) String() string { return proto.CompactTextString(m) }
func (*ImageData) ProtoMessage()    {}
func (*ImageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8eb3179769d6259, []int{0}
}

func (m *ImageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageData.Unmarshal(m, b)
}
func (m *ImageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageData.Marshal(b, m, deterministic)
}
func (m *ImageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageData.Merge(m, src)
}
func (m *ImageData) XXX_Size() int {
	return xxx_messageInfo_ImageData.Size(m)
}
func (m *ImageData) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageData.DiscardUnknown(m)
}

var xxx_messageInfo_ImageData proto.InternalMessageInfo

func (m *ImageData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImageData) GetPhoto() []byte {
	if m != nil {
		return m.Photo
	}
	return nil
}

type ImageSaveResult struct {
	RpcCode              int32    `protobuf:"varint,1,opt,name=rpc_code,json=rpcCode,proto3" json:"rpc_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageSaveResult) Reset()         { *m = ImageSaveResult{} }
func (m *ImageSaveResult) String() string { return proto.CompactTextString(m) }
func (*ImageSaveResult) ProtoMessage()    {}
func (*ImageSaveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8eb3179769d6259, []int{1}
}

func (m *ImageSaveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageSaveResult.Unmarshal(m, b)
}
func (m *ImageSaveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageSaveResult.Marshal(b, m, deterministic)
}
func (m *ImageSaveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageSaveResult.Merge(m, src)
}
func (m *ImageSaveResult) XXX_Size() int {
	return xxx_messageInfo_ImageSaveResult.Size(m)
}
func (m *ImageSaveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageSaveResult.DiscardUnknown(m)
}

var xxx_messageInfo_ImageSaveResult proto.InternalMessageInfo

func (m *ImageSaveResult) GetRpcCode() int32 {
	if m != nil {
		return m.RpcCode
	}
	return 0
}

func (m *ImageSaveResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ImageSaveResult) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ImagePath struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImagePath) Reset()         { *m = ImagePath{} }
func (m *ImagePath) String() string { return proto.CompactTextString(m) }
func (*ImagePath) ProtoMessage()    {}
func (*ImagePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8eb3179769d6259, []int{2}
}

func (m *ImagePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImagePath.Unmarshal(m, b)
}
func (m *ImagePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImagePath.Marshal(b, m, deterministic)
}
func (m *ImagePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImagePath.Merge(m, src)
}
func (m *ImagePath) XXX_Size() int {
	return xxx_messageInfo_ImagePath.Size(m)
}
func (m *ImagePath) XXX_DiscardUnknown() {
	xxx_messageInfo_ImagePath.DiscardUnknown(m)
}

var xxx_messageInfo_ImagePath proto.InternalMessageInfo

func (m *ImagePath) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ImageLoadResult struct {
	RpcCode              int32    `protobuf:"varint,1,opt,name=rpc_code,json=rpcCode,proto3" json:"rpc_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Photo                []byte   `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageLoadResult) Reset()         { *m = ImageLoadResult{} }
func (m *ImageLoadResult) String() string { return proto.CompactTextString(m) }
func (*ImageLoadResult) ProtoMessage()    {}
func (*ImageLoadResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8eb3179769d6259, []int{3}
}

func (m *ImageLoadResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageLoadResult.Unmarshal(m, b)
}
func (m *ImageLoadResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageLoadResult.Marshal(b, m, deterministic)
}
func (m *ImageLoadResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageLoadResult.Merge(m, src)
}
func (m *ImageLoadResult) XXX_Size() int {
	return xxx_messageInfo_ImageLoadResult.Size(m)
}
func (m *ImageLoadResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageLoadResult.DiscardUnknown(m)
}

var xxx_messageInfo_ImageLoadResult proto.InternalMessageInfo

func (m *ImageLoadResult) GetRpcCode() int32 {
	if m != nil {
		return m.RpcCode
	}
	return 0
}

func (m *ImageLoadResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ImageLoadResult) GetPhoto() []byte {
	if m != nil {
		return m.Photo
	}
	return nil
}

func init() {
	proto.RegisterType((*ImageData)(nil), "com.skynet.dipper.commons.grpc.image.ImageData")
	proto.RegisterType((*ImageSaveResult)(nil), "com.skynet.dipper.commons.grpc.image.ImageSaveResult")
	proto.RegisterType((*ImagePath)(nil), "com.skynet.dipper.commons.grpc.image.ImagePath")
	proto.RegisterType((*ImageLoadResult)(nil), "com.skynet.dipper.commons.grpc.image.ImageLoadResult")
}

func init() { proto.RegisterFile("ImageService.proto", fileDescriptor_c8eb3179769d6259) }

var fileDescriptor_c8eb3179769d6259 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x40, 0xbb, 0xb6, 0xb5, 0xed, 0x50, 0x50, 0x16, 0x0f, 0x51, 0x10, 0x4a, 0xf0, 0xd0, 0xd3,
	0x0a, 0x6a, 0x7f, 0xa0, 0x7a, 0x11, 0x3c, 0x94, 0x78, 0xf1, 0x20, 0xc8, 0xba, 0x3b, 0xa4, 0xc1,
	0x6c, 0x66, 0xd9, 0xdd, 0x46, 0xfc, 0x71, 0xcf, 0x92, 0xa4, 0x6d, 0x7a, 0x6c, 0xf0, 0x36, 0xb3,
	0xc3, 0xcc, 0xdb, 0x79, 0x0c, 0xf0, 0x67, 0x23, 0x53, 0x7c, 0x45, 0x57, 0x66, 0x0a, 0x85, 0x75,
	0x14, 0x88, 0xdf, 0x28, 0x32, 0xc2, 0x7f, 0xfd, 0x14, 0x18, 0x84, 0xce, 0xac, 0x45, 0x27, 0x14,
	0x19, 0x43, 0x85, 0x17, 0xa9, 0xb3, 0x4a, 0x64, 0x55, 0x4b, 0xbc, 0x80, 0x49, 0xdd, 0xfb, 0x24,
	0x83, 0xe4, 0x1c, 0x06, 0x85, 0x34, 0x18, 0xb1, 0x19, 0x9b, 0x4f, 0x92, 0x3a, 0xe6, 0x17, 0x30,
	0xb4, 0x6b, 0x0a, 0x14, 0x9d, 0xcc, 0xd8, 0x7c, 0x9a, 0x34, 0x49, 0xfc, 0x06, 0x67, 0x0d, 0x52,
	0x96, 0x98, 0xa0, 0xdf, 0xe4, 0x81, 0x5f, 0xc2, 0xd8, 0x59, 0xf5, 0xa1, 0x48, 0x37, 0x03, 0x86,
	0xc9, 0xc8, 0x59, 0xf5, 0x48, 0x1a, 0x79, 0x04, 0x23, 0x83, 0xde, 0xcb, 0x14, 0xeb, 0x29, 0x93,
	0x64, 0x97, 0xf2, 0x73, 0xe8, 0x6f, 0x5c, 0x1e, 0xf5, 0xeb, 0xd7, 0x2a, 0x8c, 0xaf, 0xb7, 0x1f,
	0x5a, 0xc9, 0xb0, 0xde, 0x95, 0x59, 0x5b, 0x7e, 0xdf, 0x82, 0x5f, 0x48, 0xea, 0xff, 0x80, 0xf7,
	0x6b, 0xf5, 0x0f, 0xd6, 0xba, 0xfb, 0x65, 0x30, 0x3d, 0x54, 0xc9, 0x2d, 0x0c, 0xbc, 0x2c, 0x91,
	0xdf, 0x8a, 0x63, 0x6c, 0x8a, 0xbd, 0xca, 0xab, 0x45, 0x87, 0x86, 0x56, 0x62, 0xdc, 0xe3, 0x01,
	0xc6, 0x9a, 0xbe, 0x8b, 0x9c, 0xa4, 0xee, 0x44, 0xad, 0x7c, 0x75, 0xa2, 0xb6, 0x06, 0xe3, 0xde,
	0xf2, 0x01, 0x8e, 0x3a, 0x97, 0x25, 0x34, 0xac, 0xea, 0xc0, 0x56, 0xec, 0xf3, 0xb4, 0xbe, 0xb4,
	0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0xb7, 0x82, 0x17, 0x7f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImageServiceClient interface {
	Save(ctx context.Context, in *ImageData, opts ...grpc.CallOption) (*ImageSaveResult, error)
	Download(ctx context.Context, in *ImagePath, opts ...grpc.CallOption) (*ImageLoadResult, error)
}

type imageServiceClient struct {
	cc *grpc.ClientConn
}

func NewImageServiceClient(cc *grpc.ClientConn) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) Save(ctx context.Context, in *ImageData, opts ...grpc.CallOption) (*ImageSaveResult, error) {
	out := new(ImageSaveResult)
	err := c.cc.Invoke(ctx, "/com.skynet.dipper.commons.grpc.image.ImageService/save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Download(ctx context.Context, in *ImagePath, opts ...grpc.CallOption) (*ImageLoadResult, error) {
	out := new(ImageLoadResult)
	err := c.cc.Invoke(ctx, "/com.skynet.dipper.commons.grpc.image.ImageService/download", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageServiceServer is the server API for ImageService service.
type ImageServiceServer interface {
	Save(context.Context, *ImageData) (*ImageSaveResult, error)
	Download(context.Context, *ImagePath) (*ImageLoadResult, error)
}

// UnimplementedImageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedImageServiceServer struct {
}

func (*UnimplementedImageServiceServer) Save(ctx context.Context, req *ImageData) (*ImageSaveResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedImageServiceServer) Download(ctx context.Context, req *ImagePath) (*ImageLoadResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}

func RegisterImageServiceServer(s *grpc.Server, srv ImageServiceServer) {
	s.RegisterService(&_ImageService_serviceDesc, srv)
}

func _ImageService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.skynet.dipper.commons.grpc.image.ImageService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Save(ctx, req.(*ImageData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImagePath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.skynet.dipper.commons.grpc.image.ImageService/Download",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Download(ctx, req.(*ImagePath))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.skynet.dipper.commons.grpc.image.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "save",
			Handler:    _ImageService_Save_Handler,
		},
		{
			MethodName: "download",
			Handler:    _ImageService_Download_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ImageService.proto",
}

// ImageServiceClientImpl is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImageServiceClientImpl struct {
	Save     func(ctx context.Context, in *ImageData, out *ImageSaveResult) error
	Download func(ctx context.Context, in *ImagePath, out *ImageLoadResult) error
}

func (c *ImageServiceClientImpl) Reference() string {
	return "imageServiceImpl"
}

func (c *ImageServiceClientImpl) GetDubboStub(cc *grpc.ClientConn) ImageServiceClient {
	return NewImageServiceClient(cc)
}

type ImageServiceProviderBase struct {
	proxyImpl protocol.Invoker
}

func (s *ImageServiceProviderBase) SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *ImageServiceProviderBase) GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func _DUBBO_ImageService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dgrpc.DubboGrpcService)
	args := []interface{}{}
	args = append(args, in)
	invo := invocation.NewRPCInvocation("Save", args, nil)
	if interceptor == nil {
		result := base.GetProxyImpl().Invoke(invo)
		return result.Result(), result.Error()
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.skynet.dipper.commons.grpc.image.ImageService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.GetProxyImpl().Invoke(invo)
		return result.Result(), result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func _DUBBO_ImageService_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImagePath)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dgrpc.DubboGrpcService)
	args := []interface{}{}
	args = append(args, in)
	invo := invocation.NewRPCInvocation("Download", args, nil)
	if interceptor == nil {
		result := base.GetProxyImpl().Invoke(invo)
		return result.Result(), result.Error()
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.skynet.dipper.commons.grpc.image.ImageService/Download",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.GetProxyImpl().Invoke(invo)
		return result.Result(), result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

func (s *ImageServiceProviderBase) ServiceDesc() *grpc.ServiceDesc {
	return &grpc.ServiceDesc{
		ServiceName: "com.skynet.dipper.commons.grpc.image.ImageService",
		HandlerType: (*ImageServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{
				MethodName: "save",
				Handler:    _DUBBO_ImageService_Save_Handler,
			},
			{
				MethodName: "download",
				Handler:    _DUBBO_ImageService_Download_Handler,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "ImageService.proto",
	}
}
