// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupMessageService.proto

package com.skynet.dipper.commons.grpc.group;

public final class GroupMessageProto {
  private GroupMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_group_GroupMessagePro_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_group_GroupMessagePro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031GroupMessageService.proto\022$com.skynet." +
      "dipper.commons.grpc.group\"\226\001\n\017GroupMessa" +
      "gePro\022\n\n\002id\030\001 \001(\005\022\017\n\007user_id\030\002 \001(\005\022\020\n\010gr" +
      "oup_id\030\003 \001(\005\022\017\n\007content\030\004 \001(\t\022\016\n\006is_del\030" +
      "\005 \001(\005\022\017\n\007is_read\030\006 \001(\005\022\021\n\tsend_time\030\007 \001(" +
      "\t\022\017\n\007is_back\030\010 \001(\0052\025\n\023GroupMessageServic" +
      "eB;\n$com.skynet.dipper.commons.grpc.grou" +
      "pB\021GroupMessageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_skynet_dipper_commons_grpc_group_GroupMessagePro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skynet_dipper_commons_grpc_group_GroupMessagePro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_group_GroupMessagePro_descriptor,
        new java.lang.String[] { "Id", "UserId", "GroupId", "Content", "IsDel", "IsRead", "SendTime", "IsBack", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
