// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImageService.proto

package com.skynet.dipper.commons.grpc.image;

public final class ImageProto {
  private ImageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_image_ImageData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_image_ImageData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_image_ImageSaveResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_image_ImageSaveResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_image_ImagePath_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_image_ImagePath_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_image_ImageLoadResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_image_ImageLoadResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ImageService.proto\022$com.skynet.dipper." +
      "commons.grpc.image\"(\n\tImageData\022\014\n\004name\030" +
      "\001 \001(\t\022\r\n\005photo\030\002 \001(\014\"A\n\017ImageSaveResult\022" +
      "\020\n\010rpc_code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\013\n\003ur" +
      "l\030\003 \001(\t\"\030\n\tImagePath\022\013\n\003url\030\001 \001(\t\"C\n\017Ima" +
      "geLoadResult\022\020\n\010rpc_code\030\001 \001(\005\022\017\n\007messag" +
      "e\030\002 \001(\t\022\r\n\005photo\030\003 \001(\0142\366\001\n\014ImageService\022" +
      "p\n\004save\022/.com.skynet.dipper.commons.grpc" +
      ".image.ImageData\0325.com.skynet.dipper.com" +
      "mons.grpc.image.ImageSaveResult\"\000\022t\n\010dow" +
      "nload\022/.com.skynet.dipper.commons.grpc.i" +
      "mage.ImagePath\0325.com.skynet.dipper.commo" +
      "ns.grpc.image.ImageLoadResult\"\000B4\n$com.s" +
      "kynet.dipper.commons.grpc.imageB\nImagePr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_skynet_dipper_commons_grpc_image_ImageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skynet_dipper_commons_grpc_image_ImageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_image_ImageData_descriptor,
        new java.lang.String[] { "Name", "Photo", });
    internal_static_com_skynet_dipper_commons_grpc_image_ImageSaveResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_skynet_dipper_commons_grpc_image_ImageSaveResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_image_ImageSaveResult_descriptor,
        new java.lang.String[] { "RpcCode", "Message", "Url", });
    internal_static_com_skynet_dipper_commons_grpc_image_ImagePath_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_skynet_dipper_commons_grpc_image_ImagePath_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_image_ImagePath_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_com_skynet_dipper_commons_grpc_image_ImageLoadResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_skynet_dipper_commons_grpc_image_ImageLoadResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_image_ImageLoadResult_descriptor,
        new java.lang.String[] { "RpcCode", "Message", "Photo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
