// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseService.proto

package com.skynet.dipper.commons.grpc.base;

public final class BaseServiceProto {
  private BaseServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_base_RpcResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_base_RpcResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_base_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_base_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_base_DataList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_base_DataList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_base_KeyId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_base_KeyId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_base_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_base_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_base_EntryList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_base_EntryList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_base_PageInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_base_PageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BaseService.proto\022#com.skynet.dipper.c" +
      "ommons.grpc.base\032\031google/protobuf/any.pr" +
      "oto\"R\n\tRpcResult\022\020\n\010rpc_code\030\001 \001(\005\022\017\n\007me" +
      "ssage\030\002 \001(\t\022\"\n\004data\030\003 \001(\0132\024.google.proto" +
      "buf.Any\"G\n\005Empty\022>\n\004type\030\001 \001(\01620.com.sky" +
      "net.dipper.commons.grpc.base.MessageType" +
      "\".\n\010DataList\022\"\n\004data\030\001 \003(\0132\024.google.prot" +
      "obuf.Any\"W\n\005KeyId\022>\n\004type\030\001 \001(\01620.com.sk" +
      "ynet.dipper.commons.grpc.base.MessageTyp" +
      "e\022\016\n\006key_id\030\002 \001(\005\"l\n\005Entry\022>\n\004type\030\001 \001(\016" +
      "20.com.skynet.dipper.commons.grpc.base.M" +
      "essageType\022#\n\005entry\030\002 \001(\0132\024.google.proto" +
      "buf.Any\"p\n\tEntryList\022>\n\004type\030\001 \001(\01620.com" +
      ".skynet.dipper.commons.grpc.base.Message" +
      "Type\022#\n\005entry\030\002 \003(\0132\024.google.protobuf.An" +
      "y\"o\n\010PageInfo\022>\n\004type\030\001 \001(\01620.com.skynet" +
      ".dipper.commons.grpc.base.MessageType\022\020\n" +
      "\010page_num\030\002 \001(\005\022\021\n\tpage_size\030\003 \001(\005*\222\001\n\013M" +
      "essageType\022\n\n\006FRIEND\020\000\022\022\n\016FRIEND_MESSAGE" +
      "\020\001\022\017\n\013FRIEND_TYPE\020\002\022\t\n\005GROUP\020\003\022\016\n\nGROUP_" +
      "USER\020\004\022\010\n\004USER\020\005\022\021\n\rGROUP_MESSAGE\020\006\022\010\n\004B" +
      "LOG\020\007\022\020\n\014BLOG_MESSAGE\020\0102\357\007\n\013BaseService\022" +
      "d\n\004save\022*.com.skynet.dipper.commons.grpc" +
      ".base.Entry\032..com.skynet.dipper.commons." +
      "grpc.base.RpcResult\"\000\022j\n\ndeleteById\022*.co" +
      "m.skynet.dipper.commons.grpc.base.KeyId\032" +
      "..com.skynet.dipper.commons.grpc.base.Rp" +
      "cResult\"\000\022t\n\024deleteByPropertyList\022*.com." +
      "skynet.dipper.commons.grpc.base.Entry\032.." +
      "com.skynet.dipper.commons.grpc.base.RpcR" +
      "esult\"\000\022f\n\006update\022*.com.skynet.dipper.co" +
      "mmons.grpc.base.Entry\032..com.skynet.dippe" +
      "r.commons.grpc.base.RpcResult\"\000\022j\n\nselec" +
      "tById\022*.com.skynet.dipper.commons.grpc.b" +
      "ase.KeyId\032..com.skynet.dipper.commons.gr" +
      "pc.base.RpcResult\"\000\022i\n\tselectAll\022*.com.s" +
      "kynet.dipper.commons.grpc.base.Empty\032..c" +
      "om.skynet.dipper.commons.grpc.base.RpcRe" +
      "sult\"\000\022p\n\020selectByProperty\022*.com.skynet." +
      "dipper.commons.grpc.base.Entry\032..com.sky" +
      "net.dipper.commons.grpc.base.RpcResult\"\000" +
      "\022t\n\024selectListByProperty\022*.com.skynet.di" +
      "pper.commons.grpc.base.Entry\032..com.skyne" +
      "t.dipper.commons.grpc.base.RpcResult\"\000\022q" +
      "\n\016selectPageList\022-.com.skynet.dipper.com" +
      "mons.grpc.base.PageInfo\032..com.skynet.dip" +
      "per.commons.grpc.base.RpcResult\"\000B9\n#com" +
      ".skynet.dipper.commons.grpc.baseB\020BaseSe" +
      "rviceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_skynet_dipper_commons_grpc_base_RpcResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skynet_dipper_commons_grpc_base_RpcResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_base_RpcResult_descriptor,
        new java.lang.String[] { "RpcCode", "Message", "Data", });
    internal_static_com_skynet_dipper_commons_grpc_base_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_skynet_dipper_commons_grpc_base_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_base_Empty_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_com_skynet_dipper_commons_grpc_base_DataList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_skynet_dipper_commons_grpc_base_DataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_base_DataList_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_com_skynet_dipper_commons_grpc_base_KeyId_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_skynet_dipper_commons_grpc_base_KeyId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_base_KeyId_descriptor,
        new java.lang.String[] { "Type", "KeyId", });
    internal_static_com_skynet_dipper_commons_grpc_base_Entry_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_skynet_dipper_commons_grpc_base_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_base_Entry_descriptor,
        new java.lang.String[] { "Type", "Entry", });
    internal_static_com_skynet_dipper_commons_grpc_base_EntryList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_skynet_dipper_commons_grpc_base_EntryList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_base_EntryList_descriptor,
        new java.lang.String[] { "Type", "Entry", });
    internal_static_com_skynet_dipper_commons_grpc_base_PageInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_skynet_dipper_commons_grpc_base_PageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_base_PageInfo_descriptor,
        new java.lang.String[] { "Type", "PageNum", "PageSize", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
