// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatService.proto

package com.skynet.dipper.commons.grpc.chat;

public interface MVFriendOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skynet.dipper.commons.grpc.chat.MVFriend)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string groupname = 1;</code>
   * @return The groupname.
   */
  java.lang.String getGroupname();
  /**
   * <code>string groupname = 1;</code>
   * @return The bytes for groupname.
   */
  com.google.protobuf.ByteString
      getGroupnameBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 online = 3;</code>
   * @return The online.
   */
  int getOnline();

  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVUser list = 4;</code>
   */
  java.util.List<com.skynet.dipper.commons.grpc.chat.MVUser> 
      getListList();
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVUser list = 4;</code>
   */
  com.skynet.dipper.commons.grpc.chat.MVUser getList(int index);
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVUser list = 4;</code>
   */
  int getListCount();
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVUser list = 4;</code>
   */
  java.util.List<? extends com.skynet.dipper.commons.grpc.chat.MVUserOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVUser list = 4;</code>
   */
  com.skynet.dipper.commons.grpc.chat.MVUserOrBuilder getListOrBuilder(
      int index);
}
