// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatService.proto

package com.skynet.dipper.commons.grpc.chat;

public interface MVInitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skynet.dipper.commons.grpc.chat.MVInit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   * 失败信息,成功则为空
   * </pre>
   *
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <pre>
   * 失败信息,成功则为空
   * </pre>
   *
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.com.skynet.dipper.commons.grpc.chat.MVData data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.com.skynet.dipper.commons.grpc.chat.MVData data = 3;</code>
   * @return The data.
   */
  com.skynet.dipper.commons.grpc.chat.MVData getData();
  /**
   * <code>.com.skynet.dipper.commons.grpc.chat.MVData data = 3;</code>
   */
  com.skynet.dipper.commons.grpc.chat.MVDataOrBuilder getDataOrBuilder();
}
