// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedisService.proto

package com.skynet.dipper.commons.grpc.redis;

public final class RedisProto {
  private RedisProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_redis_RKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_redis_RKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_redis_RPair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_redis_RPair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_redis_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_redis_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_redis_IsOK_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_redis_IsOK_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_redis_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_redis_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022RedisService.proto\022$com.skynet.dipper." +
      "commons.grpc.redis\"\023\n\004RKey\022\013\n\003key\030\001 \001(\t\"" +
      "#\n\005RPair\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\027\n\006" +
      "Result\022\r\n\005value\030\001 \001(\t\"\022\n\004IsOK\022\n\n\002ok\030\001 \001(" +
      "\010\"\007\n\005Empty2\205\004\n\014RedisService\022a\n\005exist\022*.c" +
      "om.skynet.dipper.commons.grpc.redis.RKey" +
      "\032*.com.skynet.dipper.commons.grpc.redis." +
      "IsOK\"\000\022h\n\013setIfAbsent\022+.com.skynet.dippe" +
      "r.commons.grpc.redis.RPair\032*.com.skynet." +
      "dipper.commons.grpc.redis.IsOK\"\000\022a\n\003get\022" +
      "*.com.skynet.dipper.commons.grpc.redis.R" +
      "Key\032,.com.skynet.dipper.commons.grpc.red" +
      "is.Result\"\000\022a\n\003set\022+.com.skynet.dipper.c" +
      "ommons.grpc.redis.RPair\032+.com.skynet.dip" +
      "per.commons.grpc.redis.Empty\"\000\022b\n\006delete" +
      "\022*.com.skynet.dipper.commons.grpc.redis." +
      "RKey\032*.com.skynet.dipper.commons.grpc.re" +
      "dis.IsOK\"\000B4\n$com.skynet.dipper.commons." +
      "grpc.redisB\nRedisProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_skynet_dipper_commons_grpc_redis_RKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skynet_dipper_commons_grpc_redis_RKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_redis_RKey_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_com_skynet_dipper_commons_grpc_redis_RPair_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_skynet_dipper_commons_grpc_redis_RPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_redis_RPair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_skynet_dipper_commons_grpc_redis_Result_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_skynet_dipper_commons_grpc_redis_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_redis_Result_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_com_skynet_dipper_commons_grpc_redis_IsOK_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_skynet_dipper_commons_grpc_redis_IsOK_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_redis_IsOK_descriptor,
        new java.lang.String[] { "Ok", });
    internal_static_com_skynet_dipper_commons_grpc_redis_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_skynet_dipper_commons_grpc_redis_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_redis_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
