// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatService.proto

package com.skynet.dipper.commons.grpc.chat;

/**
 * Protobuf type {@code com.skynet.dipper.commons.grpc.chat.MVData}
 */
public  final class MVData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.skynet.dipper.commons.grpc.chat.MVData)
    MVDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MVData.newBuilder() to construct.
  private MVData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MVData() {
    friend_ = java.util.Collections.emptyList();
    group_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MVData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MVData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.skynet.dipper.commons.grpc.chat.MVUser.Builder subBuilder = null;
            if (mine_ != null) {
              subBuilder = mine_.toBuilder();
            }
            mine_ = input.readMessage(com.skynet.dipper.commons.grpc.chat.MVUser.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mine_);
              mine_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              friend_ = new java.util.ArrayList<com.skynet.dipper.commons.grpc.chat.MVFriend>();
              mutable_bitField0_ |= 0x00000001;
            }
            friend_.add(
                input.readMessage(com.skynet.dipper.commons.grpc.chat.MVFriend.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              group_ = new java.util.ArrayList<com.skynet.dipper.commons.grpc.chat.MVGroup>();
              mutable_bitField0_ |= 0x00000002;
            }
            group_.add(
                input.readMessage(com.skynet.dipper.commons.grpc.chat.MVGroup.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        friend_ = java.util.Collections.unmodifiableList(friend_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        group_ = java.util.Collections.unmodifiableList(group_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skynet.dipper.commons.grpc.chat.ChatProto.internal_static_com_skynet_dipper_commons_grpc_chat_MVData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skynet.dipper.commons.grpc.chat.ChatProto.internal_static_com_skynet_dipper_commons_grpc_chat_MVData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skynet.dipper.commons.grpc.chat.MVData.class, com.skynet.dipper.commons.grpc.chat.MVData.Builder.class);
  }

  public static final int MINE_FIELD_NUMBER = 1;
  private com.skynet.dipper.commons.grpc.chat.MVUser mine_;
  /**
   * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
   * @return Whether the mine field is set.
   */
  public boolean hasMine() {
    return mine_ != null;
  }
  /**
   * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
   * @return The mine.
   */
  public com.skynet.dipper.commons.grpc.chat.MVUser getMine() {
    return mine_ == null ? com.skynet.dipper.commons.grpc.chat.MVUser.getDefaultInstance() : mine_;
  }
  /**
   * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
   */
  public com.skynet.dipper.commons.grpc.chat.MVUserOrBuilder getMineOrBuilder() {
    return getMine();
  }

  public static final int FRIEND_FIELD_NUMBER = 2;
  private java.util.List<com.skynet.dipper.commons.grpc.chat.MVFriend> friend_;
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  public java.util.List<com.skynet.dipper.commons.grpc.chat.MVFriend> getFriendList() {
    return friend_;
  }
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  public java.util.List<? extends com.skynet.dipper.commons.grpc.chat.MVFriendOrBuilder> 
      getFriendOrBuilderList() {
    return friend_;
  }
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  public int getFriendCount() {
    return friend_.size();
  }
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  public com.skynet.dipper.commons.grpc.chat.MVFriend getFriend(int index) {
    return friend_.get(index);
  }
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  public com.skynet.dipper.commons.grpc.chat.MVFriendOrBuilder getFriendOrBuilder(
      int index) {
    return friend_.get(index);
  }

  public static final int GROUP_FIELD_NUMBER = 3;
  private java.util.List<com.skynet.dipper.commons.grpc.chat.MVGroup> group_;
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  public java.util.List<com.skynet.dipper.commons.grpc.chat.MVGroup> getGroupList() {
    return group_;
  }
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  public java.util.List<? extends com.skynet.dipper.commons.grpc.chat.MVGroupOrBuilder> 
      getGroupOrBuilderList() {
    return group_;
  }
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  public int getGroupCount() {
    return group_.size();
  }
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  public com.skynet.dipper.commons.grpc.chat.MVGroup getGroup(int index) {
    return group_.get(index);
  }
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  public com.skynet.dipper.commons.grpc.chat.MVGroupOrBuilder getGroupOrBuilder(
      int index) {
    return group_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mine_ != null) {
      output.writeMessage(1, getMine());
    }
    for (int i = 0; i < friend_.size(); i++) {
      output.writeMessage(2, friend_.get(i));
    }
    for (int i = 0; i < group_.size(); i++) {
      output.writeMessage(3, group_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mine_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMine());
    }
    for (int i = 0; i < friend_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, friend_.get(i));
    }
    for (int i = 0; i < group_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, group_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skynet.dipper.commons.grpc.chat.MVData)) {
      return super.equals(obj);
    }
    com.skynet.dipper.commons.grpc.chat.MVData other = (com.skynet.dipper.commons.grpc.chat.MVData) obj;

    if (hasMine() != other.hasMine()) return false;
    if (hasMine()) {
      if (!getMine()
          .equals(other.getMine())) return false;
    }
    if (!getFriendList()
        .equals(other.getFriendList())) return false;
    if (!getGroupList()
        .equals(other.getGroupList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMine()) {
      hash = (37 * hash) + MINE_FIELD_NUMBER;
      hash = (53 * hash) + getMine().hashCode();
    }
    if (getFriendCount() > 0) {
      hash = (37 * hash) + FRIEND_FIELD_NUMBER;
      hash = (53 * hash) + getFriendList().hashCode();
    }
    if (getGroupCount() > 0) {
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroupList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skynet.dipper.commons.grpc.chat.MVData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skynet.dipper.commons.grpc.chat.MVData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.skynet.dipper.commons.grpc.chat.MVData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.skynet.dipper.commons.grpc.chat.MVData)
      com.skynet.dipper.commons.grpc.chat.MVDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skynet.dipper.commons.grpc.chat.ChatProto.internal_static_com_skynet_dipper_commons_grpc_chat_MVData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skynet.dipper.commons.grpc.chat.ChatProto.internal_static_com_skynet_dipper_commons_grpc_chat_MVData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skynet.dipper.commons.grpc.chat.MVData.class, com.skynet.dipper.commons.grpc.chat.MVData.Builder.class);
    }

    // Construct using com.skynet.dipper.commons.grpc.chat.MVData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFriendFieldBuilder();
        getGroupFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (mineBuilder_ == null) {
        mine_ = null;
      } else {
        mine_ = null;
        mineBuilder_ = null;
      }
      if (friendBuilder_ == null) {
        friend_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        friendBuilder_.clear();
      }
      if (groupBuilder_ == null) {
        group_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        groupBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skynet.dipper.commons.grpc.chat.ChatProto.internal_static_com_skynet_dipper_commons_grpc_chat_MVData_descriptor;
    }

    @java.lang.Override
    public com.skynet.dipper.commons.grpc.chat.MVData getDefaultInstanceForType() {
      return com.skynet.dipper.commons.grpc.chat.MVData.getDefaultInstance();
    }

    @java.lang.Override
    public com.skynet.dipper.commons.grpc.chat.MVData build() {
      com.skynet.dipper.commons.grpc.chat.MVData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skynet.dipper.commons.grpc.chat.MVData buildPartial() {
      com.skynet.dipper.commons.grpc.chat.MVData result = new com.skynet.dipper.commons.grpc.chat.MVData(this);
      int from_bitField0_ = bitField0_;
      if (mineBuilder_ == null) {
        result.mine_ = mine_;
      } else {
        result.mine_ = mineBuilder_.build();
      }
      if (friendBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          friend_ = java.util.Collections.unmodifiableList(friend_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.friend_ = friend_;
      } else {
        result.friend_ = friendBuilder_.build();
      }
      if (groupBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          group_ = java.util.Collections.unmodifiableList(group_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.group_ = group_;
      } else {
        result.group_ = groupBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skynet.dipper.commons.grpc.chat.MVData) {
        return mergeFrom((com.skynet.dipper.commons.grpc.chat.MVData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skynet.dipper.commons.grpc.chat.MVData other) {
      if (other == com.skynet.dipper.commons.grpc.chat.MVData.getDefaultInstance()) return this;
      if (other.hasMine()) {
        mergeMine(other.getMine());
      }
      if (friendBuilder_ == null) {
        if (!other.friend_.isEmpty()) {
          if (friend_.isEmpty()) {
            friend_ = other.friend_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFriendIsMutable();
            friend_.addAll(other.friend_);
          }
          onChanged();
        }
      } else {
        if (!other.friend_.isEmpty()) {
          if (friendBuilder_.isEmpty()) {
            friendBuilder_.dispose();
            friendBuilder_ = null;
            friend_ = other.friend_;
            bitField0_ = (bitField0_ & ~0x00000001);
            friendBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFriendFieldBuilder() : null;
          } else {
            friendBuilder_.addAllMessages(other.friend_);
          }
        }
      }
      if (groupBuilder_ == null) {
        if (!other.group_.isEmpty()) {
          if (group_.isEmpty()) {
            group_ = other.group_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureGroupIsMutable();
            group_.addAll(other.group_);
          }
          onChanged();
        }
      } else {
        if (!other.group_.isEmpty()) {
          if (groupBuilder_.isEmpty()) {
            groupBuilder_.dispose();
            groupBuilder_ = null;
            group_ = other.group_;
            bitField0_ = (bitField0_ & ~0x00000002);
            groupBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGroupFieldBuilder() : null;
          } else {
            groupBuilder_.addAllMessages(other.group_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.skynet.dipper.commons.grpc.chat.MVData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.skynet.dipper.commons.grpc.chat.MVData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.skynet.dipper.commons.grpc.chat.MVUser mine_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.skynet.dipper.commons.grpc.chat.MVUser, com.skynet.dipper.commons.grpc.chat.MVUser.Builder, com.skynet.dipper.commons.grpc.chat.MVUserOrBuilder> mineBuilder_;
    /**
     * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
     * @return Whether the mine field is set.
     */
    public boolean hasMine() {
      return mineBuilder_ != null || mine_ != null;
    }
    /**
     * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
     * @return The mine.
     */
    public com.skynet.dipper.commons.grpc.chat.MVUser getMine() {
      if (mineBuilder_ == null) {
        return mine_ == null ? com.skynet.dipper.commons.grpc.chat.MVUser.getDefaultInstance() : mine_;
      } else {
        return mineBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
     */
    public Builder setMine(com.skynet.dipper.commons.grpc.chat.MVUser value) {
      if (mineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mine_ = value;
        onChanged();
      } else {
        mineBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
     */
    public Builder setMine(
        com.skynet.dipper.commons.grpc.chat.MVUser.Builder builderForValue) {
      if (mineBuilder_ == null) {
        mine_ = builderForValue.build();
        onChanged();
      } else {
        mineBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
     */
    public Builder mergeMine(com.skynet.dipper.commons.grpc.chat.MVUser value) {
      if (mineBuilder_ == null) {
        if (mine_ != null) {
          mine_ =
            com.skynet.dipper.commons.grpc.chat.MVUser.newBuilder(mine_).mergeFrom(value).buildPartial();
        } else {
          mine_ = value;
        }
        onChanged();
      } else {
        mineBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
     */
    public Builder clearMine() {
      if (mineBuilder_ == null) {
        mine_ = null;
        onChanged();
      } else {
        mine_ = null;
        mineBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVUser.Builder getMineBuilder() {
      
      onChanged();
      return getMineFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVUserOrBuilder getMineOrBuilder() {
      if (mineBuilder_ != null) {
        return mineBuilder_.getMessageOrBuilder();
      } else {
        return mine_ == null ?
            com.skynet.dipper.commons.grpc.chat.MVUser.getDefaultInstance() : mine_;
      }
    }
    /**
     * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.skynet.dipper.commons.grpc.chat.MVUser, com.skynet.dipper.commons.grpc.chat.MVUser.Builder, com.skynet.dipper.commons.grpc.chat.MVUserOrBuilder> 
        getMineFieldBuilder() {
      if (mineBuilder_ == null) {
        mineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.skynet.dipper.commons.grpc.chat.MVUser, com.skynet.dipper.commons.grpc.chat.MVUser.Builder, com.skynet.dipper.commons.grpc.chat.MVUserOrBuilder>(
                getMine(),
                getParentForChildren(),
                isClean());
        mine_ = null;
      }
      return mineBuilder_;
    }

    private java.util.List<com.skynet.dipper.commons.grpc.chat.MVFriend> friend_ =
      java.util.Collections.emptyList();
    private void ensureFriendIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        friend_ = new java.util.ArrayList<com.skynet.dipper.commons.grpc.chat.MVFriend>(friend_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.skynet.dipper.commons.grpc.chat.MVFriend, com.skynet.dipper.commons.grpc.chat.MVFriend.Builder, com.skynet.dipper.commons.grpc.chat.MVFriendOrBuilder> friendBuilder_;

    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public java.util.List<com.skynet.dipper.commons.grpc.chat.MVFriend> getFriendList() {
      if (friendBuilder_ == null) {
        return java.util.Collections.unmodifiableList(friend_);
      } else {
        return friendBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public int getFriendCount() {
      if (friendBuilder_ == null) {
        return friend_.size();
      } else {
        return friendBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVFriend getFriend(int index) {
      if (friendBuilder_ == null) {
        return friend_.get(index);
      } else {
        return friendBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public Builder setFriend(
        int index, com.skynet.dipper.commons.grpc.chat.MVFriend value) {
      if (friendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFriendIsMutable();
        friend_.set(index, value);
        onChanged();
      } else {
        friendBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public Builder setFriend(
        int index, com.skynet.dipper.commons.grpc.chat.MVFriend.Builder builderForValue) {
      if (friendBuilder_ == null) {
        ensureFriendIsMutable();
        friend_.set(index, builderForValue.build());
        onChanged();
      } else {
        friendBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public Builder addFriend(com.skynet.dipper.commons.grpc.chat.MVFriend value) {
      if (friendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFriendIsMutable();
        friend_.add(value);
        onChanged();
      } else {
        friendBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public Builder addFriend(
        int index, com.skynet.dipper.commons.grpc.chat.MVFriend value) {
      if (friendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFriendIsMutable();
        friend_.add(index, value);
        onChanged();
      } else {
        friendBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public Builder addFriend(
        com.skynet.dipper.commons.grpc.chat.MVFriend.Builder builderForValue) {
      if (friendBuilder_ == null) {
        ensureFriendIsMutable();
        friend_.add(builderForValue.build());
        onChanged();
      } else {
        friendBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public Builder addFriend(
        int index, com.skynet.dipper.commons.grpc.chat.MVFriend.Builder builderForValue) {
      if (friendBuilder_ == null) {
        ensureFriendIsMutable();
        friend_.add(index, builderForValue.build());
        onChanged();
      } else {
        friendBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public Builder addAllFriend(
        java.lang.Iterable<? extends com.skynet.dipper.commons.grpc.chat.MVFriend> values) {
      if (friendBuilder_ == null) {
        ensureFriendIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, friend_);
        onChanged();
      } else {
        friendBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public Builder clearFriend() {
      if (friendBuilder_ == null) {
        friend_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        friendBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public Builder removeFriend(int index) {
      if (friendBuilder_ == null) {
        ensureFriendIsMutable();
        friend_.remove(index);
        onChanged();
      } else {
        friendBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVFriend.Builder getFriendBuilder(
        int index) {
      return getFriendFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVFriendOrBuilder getFriendOrBuilder(
        int index) {
      if (friendBuilder_ == null) {
        return friend_.get(index);  } else {
        return friendBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public java.util.List<? extends com.skynet.dipper.commons.grpc.chat.MVFriendOrBuilder> 
         getFriendOrBuilderList() {
      if (friendBuilder_ != null) {
        return friendBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(friend_);
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVFriend.Builder addFriendBuilder() {
      return getFriendFieldBuilder().addBuilder(
          com.skynet.dipper.commons.grpc.chat.MVFriend.getDefaultInstance());
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVFriend.Builder addFriendBuilder(
        int index) {
      return getFriendFieldBuilder().addBuilder(
          index, com.skynet.dipper.commons.grpc.chat.MVFriend.getDefaultInstance());
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
     */
    public java.util.List<com.skynet.dipper.commons.grpc.chat.MVFriend.Builder> 
         getFriendBuilderList() {
      return getFriendFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.skynet.dipper.commons.grpc.chat.MVFriend, com.skynet.dipper.commons.grpc.chat.MVFriend.Builder, com.skynet.dipper.commons.grpc.chat.MVFriendOrBuilder> 
        getFriendFieldBuilder() {
      if (friendBuilder_ == null) {
        friendBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.skynet.dipper.commons.grpc.chat.MVFriend, com.skynet.dipper.commons.grpc.chat.MVFriend.Builder, com.skynet.dipper.commons.grpc.chat.MVFriendOrBuilder>(
                friend_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        friend_ = null;
      }
      return friendBuilder_;
    }

    private java.util.List<com.skynet.dipper.commons.grpc.chat.MVGroup> group_ =
      java.util.Collections.emptyList();
    private void ensureGroupIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        group_ = new java.util.ArrayList<com.skynet.dipper.commons.grpc.chat.MVGroup>(group_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.skynet.dipper.commons.grpc.chat.MVGroup, com.skynet.dipper.commons.grpc.chat.MVGroup.Builder, com.skynet.dipper.commons.grpc.chat.MVGroupOrBuilder> groupBuilder_;

    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public java.util.List<com.skynet.dipper.commons.grpc.chat.MVGroup> getGroupList() {
      if (groupBuilder_ == null) {
        return java.util.Collections.unmodifiableList(group_);
      } else {
        return groupBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public int getGroupCount() {
      if (groupBuilder_ == null) {
        return group_.size();
      } else {
        return groupBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVGroup getGroup(int index) {
      if (groupBuilder_ == null) {
        return group_.get(index);
      } else {
        return groupBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public Builder setGroup(
        int index, com.skynet.dipper.commons.grpc.chat.MVGroup value) {
      if (groupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupIsMutable();
        group_.set(index, value);
        onChanged();
      } else {
        groupBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public Builder setGroup(
        int index, com.skynet.dipper.commons.grpc.chat.MVGroup.Builder builderForValue) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        group_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public Builder addGroup(com.skynet.dipper.commons.grpc.chat.MVGroup value) {
      if (groupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupIsMutable();
        group_.add(value);
        onChanged();
      } else {
        groupBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public Builder addGroup(
        int index, com.skynet.dipper.commons.grpc.chat.MVGroup value) {
      if (groupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupIsMutable();
        group_.add(index, value);
        onChanged();
      } else {
        groupBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public Builder addGroup(
        com.skynet.dipper.commons.grpc.chat.MVGroup.Builder builderForValue) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        group_.add(builderForValue.build());
        onChanged();
      } else {
        groupBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public Builder addGroup(
        int index, com.skynet.dipper.commons.grpc.chat.MVGroup.Builder builderForValue) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        group_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public Builder addAllGroup(
        java.lang.Iterable<? extends com.skynet.dipper.commons.grpc.chat.MVGroup> values) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, group_);
        onChanged();
      } else {
        groupBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public Builder clearGroup() {
      if (groupBuilder_ == null) {
        group_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        groupBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public Builder removeGroup(int index) {
      if (groupBuilder_ == null) {
        ensureGroupIsMutable();
        group_.remove(index);
        onChanged();
      } else {
        groupBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVGroup.Builder getGroupBuilder(
        int index) {
      return getGroupFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVGroupOrBuilder getGroupOrBuilder(
        int index) {
      if (groupBuilder_ == null) {
        return group_.get(index);  } else {
        return groupBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public java.util.List<? extends com.skynet.dipper.commons.grpc.chat.MVGroupOrBuilder> 
         getGroupOrBuilderList() {
      if (groupBuilder_ != null) {
        return groupBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(group_);
      }
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVGroup.Builder addGroupBuilder() {
      return getGroupFieldBuilder().addBuilder(
          com.skynet.dipper.commons.grpc.chat.MVGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public com.skynet.dipper.commons.grpc.chat.MVGroup.Builder addGroupBuilder(
        int index) {
      return getGroupFieldBuilder().addBuilder(
          index, com.skynet.dipper.commons.grpc.chat.MVGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
     */
    public java.util.List<com.skynet.dipper.commons.grpc.chat.MVGroup.Builder> 
         getGroupBuilderList() {
      return getGroupFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.skynet.dipper.commons.grpc.chat.MVGroup, com.skynet.dipper.commons.grpc.chat.MVGroup.Builder, com.skynet.dipper.commons.grpc.chat.MVGroupOrBuilder> 
        getGroupFieldBuilder() {
      if (groupBuilder_ == null) {
        groupBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.skynet.dipper.commons.grpc.chat.MVGroup, com.skynet.dipper.commons.grpc.chat.MVGroup.Builder, com.skynet.dipper.commons.grpc.chat.MVGroupOrBuilder>(
                group_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        group_ = null;
      }
      return groupBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.skynet.dipper.commons.grpc.chat.MVData)
  }

  // @@protoc_insertion_point(class_scope:com.skynet.dipper.commons.grpc.chat.MVData)
  private static final com.skynet.dipper.commons.grpc.chat.MVData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skynet.dipper.commons.grpc.chat.MVData();
  }

  public static com.skynet.dipper.commons.grpc.chat.MVData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MVData>
      PARSER = new com.google.protobuf.AbstractParser<MVData>() {
    @java.lang.Override
    public MVData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MVData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MVData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MVData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skynet.dipper.commons.grpc.chat.MVData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

