// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatService.proto

package com.skynet.dipper.commons.grpc.chat;

public interface MVDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skynet.dipper.commons.grpc.chat.MVData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
   * @return Whether the mine field is set.
   */
  boolean hasMine();
  /**
   * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
   * @return The mine.
   */
  com.skynet.dipper.commons.grpc.chat.MVUser getMine();
  /**
   * <code>.com.skynet.dipper.commons.grpc.chat.MVUser mine = 1;</code>
   */
  com.skynet.dipper.commons.grpc.chat.MVUserOrBuilder getMineOrBuilder();

  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  java.util.List<com.skynet.dipper.commons.grpc.chat.MVFriend> 
      getFriendList();
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  com.skynet.dipper.commons.grpc.chat.MVFriend getFriend(int index);
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  int getFriendCount();
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  java.util.List<? extends com.skynet.dipper.commons.grpc.chat.MVFriendOrBuilder> 
      getFriendOrBuilderList();
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVFriend friend = 2;</code>
   */
  com.skynet.dipper.commons.grpc.chat.MVFriendOrBuilder getFriendOrBuilder(
      int index);

  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  java.util.List<com.skynet.dipper.commons.grpc.chat.MVGroup> 
      getGroupList();
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  com.skynet.dipper.commons.grpc.chat.MVGroup getGroup(int index);
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  int getGroupCount();
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  java.util.List<? extends com.skynet.dipper.commons.grpc.chat.MVGroupOrBuilder> 
      getGroupOrBuilderList();
  /**
   * <code>repeated .com.skynet.dipper.commons.grpc.chat.MVGroup group = 3;</code>
   */
  com.skynet.dipper.commons.grpc.chat.MVGroupOrBuilder getGroupOrBuilder(
      int index);
}
