// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedisService.proto

package com.skynet.dipper.commons.grpc.redis;

public interface IsOKOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skynet.dipper.commons.grpc.redis.IsOK)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  boolean getOk();
}
