// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedisService.proto

package com.skynet.dipper.commons.grpc.redis;

public interface RKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skynet.dipper.commons.grpc.redis.RKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
