// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BlogService.proto

package com_skynet_dipper_commons_grpc_blog

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

import (
	_ "github.com/apache/dubbo-go/config"
	"github.com/apache/dubbo-go/protocol"
	_ "github.com/apache/dubbo-go/protocol/invocation"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlogPro struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Header               string   `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	BuildTime            string   `protobuf:"bytes,6,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogPro) Reset()         { *m = BlogPro{} }
func (m *BlogPro) String() string { return proto.CompactTextString(m) }
func (*BlogPro) ProtoMessage()    {}
func (*BlogPro) Descriptor() ([]byte, []int) {
	return fileDescriptor_c71e800f31ff5594, []int{0}
}

func (m *BlogPro) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogPro.Unmarshal(m, b)
}
func (m *BlogPro) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogPro.Marshal(b, m, deterministic)
}
func (m *BlogPro) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogPro.Merge(m, src)
}
func (m *BlogPro) XXX_Size() int {
	return xxx_messageInfo_BlogPro.Size(m)
}
func (m *BlogPro) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogPro.DiscardUnknown(m)
}

var xxx_messageInfo_BlogPro proto.InternalMessageInfo

func (m *BlogPro) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlogPro) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BlogPro) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *BlogPro) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *BlogPro) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *BlogPro) GetBuildTime() string {
	if m != nil {
		return m.BuildTime
	}
	return ""
}

func init() {
	proto.RegisterType((*BlogPro)(nil), "com.skynet.dipper.commons.grpc.blog.BlogPro")
}

func init() { proto.RegisterFile("BlogService.proto", fileDescriptor_c71e800f31ff5594) }

var fileDescriptor_c71e800f31ff5594 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0xc9, 0xea, 0x66, 0xd9, 0x11, 0x05, 0x83, 0x68, 0x1a, 0xe1, 0xd0, 0xe6, 0xaa, 0x14,
	0xe7, 0x1b, 0x6c, 0x67, 0x77, 0x9c, 0xf6, 0xc7, 0x6d, 0x32, 0xc4, 0xc1, 0x4d, 0x26, 0x64, 0x73,
	0x82, 0x8f, 0xe2, 0xdb, 0xca, 0xc5, 0x15, 0x2c, 0x2d, 0xbf, 0xef, 0x67, 0x8a, 0x6f, 0xe0, 0x7a,
	0x98, 0xd8, 0xbf, 0x60, 0xfe, 0x20, 0x8b, 0x26, 0x65, 0x2e, 0xac, 0x1e, 0x2d, 0x07, 0x33, 0xbf,
	0x7f, 0x46, 0x2c, 0xc6, 0x51, 0x4a, 0x98, 0x8d, 0xe5, 0x10, 0x38, 0xce, 0xc6, 0xe7, 0x64, 0xcd,
	0x38, 0xb1, 0x7f, 0xf8, 0x12, 0xd0, 0x9d, 0x4e, 0xb7, 0x99, 0xd5, 0x15, 0x34, 0xe4, 0xb4, 0x58,
	0x89, 0x75, 0xbb, 0x6b, 0xc8, 0xa9, 0x3b, 0xe8, 0x8e, 0x33, 0xe6, 0x3d, 0x39, 0xdd, 0x54, 0x29,
	0x4f, 0xf8, 0xec, 0xd4, 0x2d, 0xc8, 0x37, 0x3c, 0x38, 0xcc, 0xfa, 0x6c, 0x25, 0xd6, 0xfd, 0x6e,
	0x21, 0xa5, 0xa1, 0xb3, 0x1c, 0x0b, 0xc6, 0xa2, 0xcf, 0xeb, 0xf0, 0x8b, 0xea, 0x06, 0x5a, 0x0a,
	0x07, 0x8f, 0xba, 0xad, 0xfe, 0x07, 0xd4, 0x3d, 0xc0, 0x78, 0xa4, 0xc9, 0xed, 0x0b, 0x05, 0xd4,
	0xb2, 0x4e, 0x7d, 0x35, 0xaf, 0x14, 0x70, 0x73, 0x09, 0x17, 0x7f, 0xaa, 0x86, 0x0d, 0xfc, 0xa7,
	0x68, 0xe8, 0x97, 0x9c, 0xc2, 0x5b, 0x31, 0xca, 0xfa, 0x8a, 0xa7, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe4, 0xb0, 0x92, 0x72, 0x1f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogServiceClient is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServiceClient interface {
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

// BlogServiceServer is the server API for BlogService service.
type BlogServiceServer interface {
}

// UnimplementedBlogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogServiceServer struct {
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.skynet.dipper.commons.grpc.blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "BlogService.proto",
}

// BlogServiceClientImpl is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServiceClientImpl struct {
}

func (c *BlogServiceClientImpl) Reference() string {
	return "blogServiceImpl"
}

func (c *BlogServiceClientImpl) GetDubboStub(cc *grpc.ClientConn) BlogServiceClient {
	return NewBlogServiceClient(cc)
}

type BlogServiceProviderBase struct {
	proxyImpl protocol.Invoker
}

func (s *BlogServiceProviderBase) SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *BlogServiceProviderBase) GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *BlogServiceProviderBase) ServiceDesc() *grpc.ServiceDesc {
	return &grpc.ServiceDesc{
		ServiceName: "com.skynet.dipper.commons.grpc.blog.BlogService",
		HandlerType: (*BlogServiceServer)(nil),
		Methods:     []grpc.MethodDesc{},
		Streams:     []grpc.StreamDesc{},
		Metadata:    "BlogService.proto",
	}
}
