// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseService.proto

package proto;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skynet.commons.grpc.dipper.proto.Empty)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.skynet.commons.grpc.dipper.proto.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.skynet.commons.grpc.dipper.proto.MessageType type = 1;</code>
   * @return The type.
   */
  MessageType getType();
}
