// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImageService.proto

package proto;

public final class ImageProto {
  private ImageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_commons_grpc_dipper_proto_ImageData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_commons_grpc_dipper_proto_ImageData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_commons_grpc_dipper_proto_ImageSaveResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_commons_grpc_dipper_proto_ImageSaveResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_commons_grpc_dipper_proto_ImagePath_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_commons_grpc_dipper_proto_ImagePath_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_commons_grpc_dipper_proto_ImageLoadResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_commons_grpc_dipper_proto_ImageLoadResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022ImageService.proto\022$com.skynet.commons" +
      ".grpc.dipper.proto\"(\n\tImageData\022\014\n\004name\030" +
      "\001 \001(\t\022\r\n\005photo\030\002 \001(\014\"A\n\017ImageSaveResult\022" +
      "\020\n\010rpc_code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\013\n\003ur" +
      "l\030\003 \001(\t\"\030\n\tImagePath\022\013\n\003url\030\001 \001(\t\"C\n\017Ima" +
      "geLoadResult\022\020\n\010rpc_code\030\001 \001(\005\022\017\n\007messag" +
      "e\030\002 \001(\t\022\r\n\005photo\030\003 \001(\0142\366\001\n\014ImageService\022" +
      "p\n\004save\022/.com.skynet.commons.grpc.dipper" +
      ".proto.ImageData\0325.com.skynet.commons.gr" +
      "pc.dipper.proto.ImageSaveResult\"\000\022t\n\010dow" +
      "nload\022/.com.skynet.commons.grpc.dipper.p" +
      "roto.ImagePath\0325.com.skynet.commons.grpc" +
      ".dipper.proto.ImageLoadResult\"\000B4\n$com.s" +
      "kynet.commons.grpc.dipper.protoB\nImagePr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_skynet_commons_grpc_dipper_proto_ImageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skynet_commons_grpc_dipper_proto_ImageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_commons_grpc_dipper_proto_ImageData_descriptor,
        new String[] { "Name", "Photo", });
    internal_static_com_skynet_commons_grpc_dipper_proto_ImageSaveResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_skynet_commons_grpc_dipper_proto_ImageSaveResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_commons_grpc_dipper_proto_ImageSaveResult_descriptor,
        new String[] { "RpcCode", "Message", "Url", });
    internal_static_com_skynet_commons_grpc_dipper_proto_ImagePath_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_skynet_commons_grpc_dipper_proto_ImagePath_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_commons_grpc_dipper_proto_ImagePath_descriptor,
        new String[] { "Url", });
    internal_static_com_skynet_commons_grpc_dipper_proto_ImageLoadResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_skynet_commons_grpc_dipper_proto_ImageLoadResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_commons_grpc_dipper_proto_ImageLoadResult_descriptor,
        new String[] { "RpcCode", "Message", "Photo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
