// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.skynet.dipper.commons.grpc.user;

public interface LoginInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skynet.dipper.commons.grpc.user.LoginInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_name = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string user_name = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
