// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FriendTypeService.proto

package com.skynet.dipper.commons.grpc.friend;

public final class FriendTypeProto {
  private FriendTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_friend_FriendTypePro_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_friend_FriendTypePro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027FriendTypeService.proto\022%com.skynet.di" +
      "pper.commons.grpc.friend\"g\n\rFriendTypePr" +
      "o\022\n\n\002id\030\001 \001(\005\022\021\n\ttype_name\030\002 \001(\t\022\017\n\007user" +
      "_id\030\003 \001(\005\022\022\n\nbuild_time\030\004 \001(\t\022\022\n\nis_defa" +
      "ult\030\005 \001(\0052\023\n\021FriendTypeServiceB:\n%com.sk" +
      "ynet.dipper.commons.grpc.friendB\017FriendT" +
      "ypeProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_skynet_dipper_commons_grpc_friend_FriendTypePro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skynet_dipper_commons_grpc_friend_FriendTypePro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_friend_FriendTypePro_descriptor,
        new java.lang.String[] { "Id", "TypeName", "UserId", "BuildTime", "IsDefault", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
