// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FriendMessageService.proto

package com.skynet.dipper.commons.grpc.friend;

public final class FriendMessageProto {
  private FriendMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skynet_dipper_commons_grpc_friend_FriendMessagePro_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skynet_dipper_commons_grpc_friend_FriendMessagePro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032FriendMessageService.proto\022%com.skynet" +
      ".dipper.commons.grpc.friend\"\236\001\n\020FriendMe" +
      "ssagePro\022\n\n\002id\030\001 \001(\005\022\024\n\014from_user_id\030\002 \001" +
      "(\005\022\022\n\nto_user_id\030\003 \001(\005\022\017\n\007content\030\004 \001(\t\022" +
      "\021\n\tsend_time\030\005 \001(\t\022\017\n\007is_read\030\006 \001(\005\022\016\n\006i" +
      "s_del\030\007 \001(\005\022\017\n\007is_back\030\010 \001(\0052\026\n\024FriendMe" +
      "ssageServiceB=\n%com.skynet.dipper.common" +
      "s.grpc.friendB\022FriendMessageProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_skynet_dipper_commons_grpc_friend_FriendMessagePro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skynet_dipper_commons_grpc_friend_FriendMessagePro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skynet_dipper_commons_grpc_friend_FriendMessagePro_descriptor,
        new java.lang.String[] { "Id", "FromUserId", "ToUserId", "Content", "SendTime", "IsRead", "IsDel", "IsBack", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
