// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package proto;

public interface UserProOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skynet.commons.grpc.dipper.proto.UserPro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string user_name = 2;</code>
   * @return The userName.
   */
  String getUserName();
  /**
   * <code>string user_name = 2;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string nick_name = 4;</code>
   * @return The nickName.
   */
  String getNickName();
  /**
   * <code>string nick_name = 4;</code>
   * @return The bytes for nickName.
   */
  com.google.protobuf.ByteString
      getNickNameBytes();

  /**
   * <code>int32 gender = 5;</code>
   * @return The gender.
   */
  int getGender();

  /**
   * <code>string avatar = 6;</code>
   * @return The avatar.
   */
  String getAvatar();
  /**
   * <code>string avatar = 6;</code>
   * @return The bytes for avatar.
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>string email = 7;</code>
   * @return The email.
   */
  String getEmail();
  /**
   * <code>string email = 7;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phone = 8;</code>
   * @return The phone.
   */
  String getPhone();
  /**
   * <code>string phone = 8;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string role_code = 9;</code>
   * @return The roleCode.
   */
  String getRoleCode();
  /**
   * <code>string role_code = 9;</code>
   * @return The bytes for roleCode.
   */
  com.google.protobuf.ByteString
      getRoleCodeBytes();

  /**
   * <code>string version = 10;</code>
   * @return The version.
   */
  String getVersion();
  /**
   * <code>string version = 10;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string sign = 11;</code>
   * @return The sign.
   */
  String getSign();
  /**
   * <code>string sign = 11;</code>
   * @return The bytes for sign.
   */
  com.google.protobuf.ByteString
      getSignBytes();
}
